require('dotenv').config();
const mongoose = require('mongoose');
const Product  = require('./models/Product');

const catalog = [
  { name:'OBSIDIAN ROSE', category:'Women', subcategory:'Fragrance', price:'$210', stock:100, description:'A dark floral paradox — smoldering velvet petals suspended in shadow. Bruised Turkish rose absolute meets blackened oud resin and volcanic mineral facets, opening with smoked iris and blackcurrant.' },
  { name:'SILK & ASH EAU DE PARFUM', category:'Women', subcategory:'Fragrance', price:'$240', stock:100, description:'The scent of still air after fire — mineral, intimate, quietly luminous. A proprietary Silk Accord of musks, white sandalwood, and satin aldehyde forms a luminous mid-layer with a second-skin quality.' },
  { name:'SAFFRON NOIR CONCENTRATE', category:'Women', subcategory:'Fragrance', price:'$260', stock:75, description:'Pure pigment for the air — a dense, resinous portrait of saffron and shadow. At triple the concentration of a standard EDP, raw saffron, metallic leather, and cardamom collide in an opulent opening.' },
  { name:'MERCURIAL JASMINE', category:'Women', subcategory:'Fragrance', price:'$195', stock:100, description:'Jasmine in flux — effervescent, shifting, and endlessly alive. A dual-phase accord of Sambac absolute and Grandiflorum captures the flower simultaneously innocent and indolic, luminous and shadowed.' },
  { name:'PETRICHOR BLOOM', category:'Women', subcategory:'Fragrance', price:'$225', stock:80, description:'The precise moment rain meets earth — bottled and made eternal. A proprietary Geosmin Accord recreates the aromatic compounds released by earth and moss when activated by water.' },
  { name:'ARCHITECTURAL SYMMETRY PALETTE', category:'Women', subcategory:'Makeup', group:'Eye', price:'$85', stock:60, description:'Ten shadows engineered for dimension. Micronized Mineral Matrix technology delivers 100% crease-proof, fallout-free wear for 18+ hours across five velvet matte and five prismatic finishes.' },
  { name:'LIQUID GRAPHITE LINER', category:'Women', subcategory:'Makeup', group:'Eye', price:'$32', stock:120, description:'Architectural control in a single stroke. A 0.1mm ultra-precision brush tip delivers razor-sharp lines in carbon-black pigment suspended in flexible film polymer. 36-hour waterproof wear.' },
  { name:'FIBER EXTENSION POLYMER', category:'Women', subcategory:'Makeup', group:'Eye', price:'$28', stock:150, description:'Length beyond biology. Plant-derived cellulose microfibers extend lash length by up to 300% while a smart-set polymer locks lash architecture instantly without smudge or transfer.' },
  { name:'PIGMENTED DUST CONCENTRATE', category:'Women', subcategory:'Makeup', group:'Eye', price:'$24', stock:90, description:'Pure pigment, uncut — pressed into dust, worn like light. Milled to sub-5-micron particle size for luminosity that appears to emanate from beneath the skin. Apply dry or wet.' },
  { name:'SECOND-SKIN EMULSION', category:'Women', subcategory:'Makeup', group:'Face', price:'$56', stock:80, description:'Not a foundation — a second skin. Invisible by design, flawless in execution. Biomimetic Skin Matrix technology delivers buildable medium-to-full coverage in 52 shades.' },
  { name:'RADIANCE CORRECTION FLUID', category:'Women', subcategory:'Makeup', group:'Face', price:'$48', stock:90, description:'Part serum, part concealer — full luminosity, total correction. A Photon Diffusion Complex simultaneously conceals and treats discoloration, dark circles, and hyperpigmentation.' },
  { name:'LIQUID PHOTON ILLUMINATOR', category:'Women', subcategory:'Makeup', group:'Face', price:'$45', stock:100, description:'Pure concentrated light — suspended in serum, worn on skin. A Prismatic Particle Complex of borosilicate pearls catches and refracts light at every angle for a diffused, lit-from-within glow.' },
  { name:'SHADOW DEFINITION CREME', category:'Women', subcategory:'Makeup', group:'Face', price:'$38', stock:85, description:'Creme-to-powder shadow sculpting that respects the architecture of every face. Adaptive Tone Technology reads ambient skin temperature to adjust blending behavior for a 16-hour natural finish.' },
  { name:'SUN-ETCHED MINERAL POWDER', category:'Women', subcategory:'Makeup', group:'Face', price:'$52', stock:70, description:'The memory of sun translated into mineral pigment. A Thermal Gradient Pigment System reveals three tonal layers progressively as you build, replicating dimensional sun color.' },
  { name:'VELVET MATTE PIGMENT', category:'Women', subcategory:'Makeup', group:'Lip', price:'$38', stock:130, description:'Color at its most absolute — weightless, waterproof, and irreversibly vivid. Soft-Matte Film Technology dries transfer-proof while an embedded Lip Barrier Complex delivers 12-hour hydration.' },
  { name:'CRYSTALLINE REFLECTION GLAZE', category:'Women', subcategory:'Makeup', group:'Lip', price:'$32', stock:110, description:'Pure refracted light worn on lips like liquid crystal. A Crystal Clarity Complex of prismatic glass microspheres bends light, creating holographic shine. Plumping peptides included.' },
  { name:'STRUCTURAL DEFENDER PENCIL', category:'Women', subcategory:'Makeup', group:'Lip', price:'$22', stock:140, description:'The invisible architecture behind every perfect lip. An Anti-Bleeding Barrier Complex creates a molecular seal at the lip line. Peptide ceramides and vitamin E nourish and condition. 30 shades.' },
  { name:'VOLUMIZING PEPTIDE INFUSION', category:'Women', subcategory:'Makeup', group:'Lip', price:'$40', stock:95, description:'Clinical plumping. Serum-level care. Three clinically validated peptides combine for visible plumping within 20 minutes and measurable volume increase after 28 days of daily use.' },
  { name:'DURALAST INK STAIN', category:'Women', subcategory:'Makeup', group:'Lip', price:'$28', stock:120, description:'Stains like ink. Wears like memory. A Bio-Chromatic Stain Complex molecularly binds to lip keratin proteins for 24+ hour wear with zero transfer through eating, drinking, and swimming.' },
  { name:'LIPID RECOVERY OIL', category:'Women', subcategory:'Makeup', group:'Lip', price:'$36', stock:85, description:'Concentrated lipid therapy for lips that have forgotten their softness. Ten plant-derived fatty acids including buriti, rosehip, and marula replenish the lip barrier. Visible results overnight.' },
  { name:'KINETIC BRONZING VEIL', category:'Women', subcategory:'Makeup', group:'Cheek', price:'$42', stock:75, description:'Sun-warmth in motion — a bronzer that moves with light. Chromatic Warmth Technology blends terracotta, amber, and golden-copper mineral pigments calibrated per shade. Cloud-soft texture.' },
  { name:'SUB-DERMAL FLUSH ELIXIR', category:'Women', subcategory:'Makeup', group:'Cheek', price:'$35', stock:90, description:'The blush that lives beneath — so natural it looks biological. Micro-Chromatic Dispersion technology delivers color at a particle size so fine it appears to originate within the dermis.' },
  { name:'IRIDIUM GLOW CONCENTRATE', category:'Women', subcategory:'Makeup', group:'Cheek', price:'$48', stock:65, description:'Rare-earth luminosity pressed into precision. An Iridium Particle Complex of borosilicate micro-pearls and rare-earth oxide pigments creates multi-directional spectral refraction.' },
  { name:'DEPTH PERSPECTIVE SCULPT', category:'Women', subcategory:'Makeup', group:'Cheek', price:'$45', stock:80, description:'Shadow and light in one instrument. A dual-ended stick in a Thermal-Response Creme Matrix that becomes workable with skin heat and sets to soft-focus powder in 45 seconds.' },
  { name:'MALAR STRUCTURE COMPENDIUM', category:'Women', subcategory:'Makeup', group:'Cheek', price:'$55', stock:60, description:'A complete architecture of cheek — contour, blush, and highlight in one compact. Six tonally harmonized shades with face-shape mapping diagram and two precision mini-brushes.' },
  { name:'MERIDIAN EAU DE PARFUM', category:'Men', subcategory:'Fragrance', price:'$180', stock:90, description:'Structured, grounded, and unmistakably present. A cool mineral-vetiver accord opens with bergamot and black cardamom before settling into smoked cedar and an Atlas Cedar Complex base.' },
  { name:'ATMOSPHERIC REFRESHER MIST', category:'Men', subcategory:'Fragrance', price:'$75', stock:120, description:'Reset the air around you. Silver-ion antibacterial complex neutralizes odor on skin and fabric. Hyaluronic acid hydrates with each spray. Aquatic mint, cold cedarwood, eucalyptus.' },
  { name:'RAW FORM SHAVE RECOVERY SYSTEM', category:'Men', subcategory:'Grooming', price:'$95', stock:70, description:'Engineering precision into every stage of the shave. Pre-Shave Conditioning Oil, Biomimetic Shave Creme, and Peptide Recovery Elixir work in sequence as a three-stage closed-loop ritual.' },
  { name:'Photon Shield Sunscreen SPF 50+', category:'Health And Skin Care', price:'$42', stock:150, description:'The last barrier between your skin and the sky. Adaptive Mineral Matrix of non-nano zinc oxide and titanium dioxide provides full-spectrum protection with zero white cast on all skin tones.' },
  { name:'Mineral Mist', category:'Health And Skin Care', price:'$28', stock:130, description:'Pure mineral water, charged with hydration actives. Deep-earth silica spring water enriched with Tri-Mineral Complex of magnesium, selenium, and zinc. Calms, sets makeup, and hydrates.' },
  { name:'Somatic Sleep Aid', category:'Health And Skin Care', price:'$68', stock:100, description:'Science-backed stillness for deeper sleep. Magnesium glycinate 200mg, ashwagandha KSM-66 300mg, L-theanine 200mg, and precision-dosed melatonin 0.5mg. Non-habit forming.' },
  { name:'pH Equilibrium Cleanser', category:'Health And Skin Care', price:'$35', stock:120, description:'A cleanser calibrated to the exact chemistry of your skin at pH 4.7. Sulfate-free glucoside surfactants with post-cleanse Bio-Barrier Restore Complex of ceramide-3 and lactic acid.' },
  { name:'Niacinamide Flux 10% + Zinc', category:'Health And Skin Care', price:'$52', stock:110, description:'The gold standard of pore refinement. Encapsulated niacinamide 10% with zinc PCA 1%, glycolic acid 2%, and hyaluronic acid. Visible pore reduction in 14 days. Clinical grade.' },
  { name:'Recovery Salve Post-Workout Balm', category:'Health And Skin Care', price:'$48', stock:90, description:'The last step of every great workout. Menthol 3% for immediate cooling plus arnica, turmeric, and boswellic acid for prolonged anti-inflammation. Shea butter and ceramide-1 repair skin.' },
  { name:'Probiotic Kult Microbiome Complex', category:'Health And Skin Care', price:'$72', stock:85, description:'A precision probiotic for the gut-skin axis. Twelve strains at 50 billion CFU selected for skin outcomes. Acid-resistant capsule ensures 95% viability. XOS prebiotic drives colonization.' },
  { name:'Liquid Chlorophyll Drops', category:'Health And Skin Care', price:'$38', stock:100, description:'Botanical detoxification at maximum concentration. Sodium copper chlorophyllin 100mg per serving with zinc gluconate, dandelion root, and vitamin B12. Natural mint flavor.' },
  { name:'Adaptogen Equilibrium Blend', category:'Health And Skin Care', price:'$65', stock:80, description:'Five evidence-based adaptogens targeting the HPA axis: Ashwagandha KSM-66 300mg, Rhodiola Rosea, Eleuthero, Holy Basil, and Schisandra Berry for cortisol resilience.' },
  { name:'Botanical Nootropic Clarity Complex', category:'Health And Skin Care', price:'$70', stock:75, description:'Plant-derived clarity. Lion\'s Mane 500mg, Bacopa monnieri 45% bacosides, phosphatidylserine 100mg, and Ginkgo biloba 24% flavone glycosides. Caffeine-free. Zero crash.' },
  { name:'Marine Collagen Peptide Complex', category:'Health And Skin Care', price:'$85', stock:90, description:'10g of hydrolyzed marine collagen peptides at 2kDa from wild-caught North Atlantic cod. Vitamin C 200mg, hyaluronic acid 80mg, and biotin 2500mcg complete the synthesis ecosystem.' },
  { name:'Anti-Oxidant Resin Complex', category:'Health And Skin Care', price:'$78', stock:70, description:'Four simultaneous antioxidant pathways: astaxanthin 12mg, sulforaphane, ubiquinol CoQ10 200mg, and vitamin C 500mg plus alpha lipoic acid 300mg. Comprehensive free-radical defense.' },
  { name:'Molecular Keratin Supplement', category:'Health And Skin Care', price:'$80', stock:65, description:'Cynatine HNS 500mg via patented cold-alkaline process. Clinically shown to increase hair tensile strength by 47% and reduce hair loss by 30% in 90 days. With MSM 500mg and saw palmetto.' },
  { name:'Scalp Microbiome Balancing Drops', category:'Health And Skin Care', price:'$55', stock:85, description:'Inulin, XOS, and lactobacillus ferment lysate restore beneficial scalp bacteria. Piroctone Olamine 1% controls Malassezia. Niacinamide 2% reduces scalp inflammation and sebum.' },
  { name:'Chelating Hard Water Rinse', category:'Health And Skin Care', price:'$38', stock:95, description:'EDTA, phytic acid, and citric acid strip calcium, magnesium, and iron deposits from the hair shaft — the leading cause of dullness, color brassiness, and product inefficacy.' },
  { name:'Herbal DHT Blocker Concentrate', category:'Health And Skin Care', price:'$62', stock:80, description:'Saw palmetto 320mg inhibits 5-alpha reductase. Pumpkin seed oil 500mg adds complementary inhibition. Nettle root 300mg binds SHBG. Pygeum 100mg reduces follicular inflammation.' },
  { name:'Colloidal Oatmeal Bath Soak', category:'Baby care', price:'$34', stock:110, description:'Ultra-milled colloidal oatmeal at 98% particle reduction disperses fully into bathwater, making avenanthramide anti-inflammatory and beta-glucan barrier-sealing compounds bioavailable to skin.' },
  { name:'Unscented Bath Cubes', category:'Baby care', price:'$28', stock:130, description:'Pharmaceutical-grade magnesium sulfate, sodium bicarbonate, and jojoba ester. No surfactants, no fragrance, no preservatives. Pre-portioned cubes for consistent dosing every bath. Safe from birth.' },
  { name:'Ceramide Barrier Cream', category:'Baby care', price:'$38', stock:100, description:'Physiological Ceramide Triad at 1:2:1 ratio alongside cholesterol and linoleic acid for complete lipid barrier restoration. Rich whipped texture absorbs fully. Pediatric dermatologist tested.' },
  { name:'Zinc Oxide Targeted Paste', category:'Baby care', price:'$26', stock:120, description:'Pharmaceutical-grade zinc oxide at 40% creates a complete occlusive seal. Bisabolol, calendula, and allantoin actively reduce inflammation and accelerate epidermal repair. Safe from birth.' },
  { name:'Hypoallergenic Squalane Baby Oil', category:'Baby care', price:'$32', stock:115, description:'99.9% pure plant-derived squalane from sugar cane fermentation — the least allergenic oil for infant skin. Breathable barrier for face, body, scalp cradle cap, and massage. Safe from birth.' },
  { name:'Calming Lavender Sleep Oil', category:'Baby care', price:'$30', stock:105, description:'Lavandula angustifolia and Roman chamomile at a safe 0.5% essential oil concentration in squalane — effective at engaging the parasympathetic sleep response without sensitization risk. From 3 months.' },
  { name:'Soap-Free Botanical Wash', category:'Baby care', price:'$24', stock:140, description:'Formulated at pH 5.0 using amino acid surfactants. Oat extract, calendula, and green tea polyphenols add anti-inflammatory protection. Hair and body in one formula. Safe from birth.' },
  { name:'Tear-Free Scalp Foam', category:'Baby care', price:'$22', stock:130, description:'Pre-formed mousse eliminates friction on the scalp. Amphoteric surfactants are tear-free by molecular design. Niacinamide 1% and zinc PCA 0.5% gently manage cradle cap. Safe from birth.' },
  { name:'Probiotic Baby Lotion', category:'Baby care', price:'$28', stock:110, description:'Lactobacillus Ferment Lysate and inulin prebiotic support the infant skin microbiome that educates the immune system. Ceramide-3, sunflower seed oil, and glycerin provide moisture and structure.' },
  { name:'Shea & Aloe Moisturizing Stick', category:'Baby care', price:'$18', stock:150, description:'Unrefined shea butter, aloe vera leaf juice, calendula, and bisabolol in a solid stick. Swipe directly onto dry cheeks, elbows, chapped lips, or anywhere skin needs instant relief. Safe from birth.' },
  { name:'Volcanic Ash Texturizing Paste', category:'Hair care', price:'$38', stock:95, description:'Cosmetic-grade volcanic pumice ash creates genuine mechanical hold through inter-strand friction. Medium-to-strong hold, fully re-workable throughout the day without hardening or flaking.' },
  { name:'Caffeine & Biotin Growth Tonic', category:'Hair care', price:'$45', stock:90, description:'Caffeine 0.2% inhibits DHT-pathway activity at the follicle. Redensyl patented stem cell activator reactivates dormant follicles into anagen phase. Niacinamide 3% boosts scalp circulation.' },
  { name:'Matte Charcoal Dry Shampoo', category:'Hair care', price:'$32', stock:120, description:'Activated bamboo charcoal with massive surface area adsorbs oil, odor, and buildup irreversibly. Particle-size engineered for zero black residue on any hair color. Silica lifts roots for volume.' },
  { name:'Beard & Scalp Clarifying Wash', category:'Hair care', price:'$35', stock:100, description:'Sodium Lauryl Sulfoacetate, Zinc Pyrithione 1%, and Salicylic Acid 1% address dandruff and beard flake at both scalp and beard simultaneously. Glycerin and aloe prevent post-wash dryness.' },
  { name:'Silk Peptide Glossing Serum', category:'Hair care', price:'$42', stock:85, description:'Hydrolyzed silk protein 5% physically aligns the hair cuticle scale-by-scale for uniform mirror-level light reflection. Buildup-free silicone alternative and camellia oil add warmth to the shine.' },
  { name:'Midnight Camellia Hair Mask', category:'Hair care', price:'$55', stock:70, description:'Cold-pressed camellia oil at 82% oleic acid carries a Keratin Repair Matrix and bond-building complex that reforms broken disulfide cortical bonds for genuine structural improvement overnight.' },
  { name:'Oud & Rose Infused Shine Oil', category:'Hair care', price:'$60', stock:75, description:'72-hour cold-process infusion of oud wood and rose petal absolute into a tri-oil base of marula, argan, and squalane. Wear as a hair finishing oil, luxury body oil, or fragrance layer.' },
  { name:'Heat Defense Poly-Thermal Mist', category:'Hair care', price:'$36', stock:110, description:'Validated protection to 450F / 230C via Poly-Thermal Shield: silicone matrix reflects heat at the cuticle, wheat protein distributes it evenly, ceramide moisture lock prevents cortical damage.' },
];

mongoose.connect(process.env.MONGO_URI).then(async () => {
  let created = 0, skipped = 0;
  for (const item of catalog) {
    const exists = await Product.findOne({ name: item.name });
    if (exists) { skipped++; continue; }
    await Product.create({ ...item, image: '', featured: false });
    created++;
  }
  console.log(`Done — created: ${created} | skipped (already exist): ${skipped}`);
  process.exit(0);
}).catch(e => { console.error(e.message); process.exit(1); });
